  dev[m
  feat/add-validate-props[m
  feat/auto-keycode-mapping[m
  feat/element-align-attr[m
  feat/run-blits-tests-workflow[m
  feat/warn-non-existing-props[m
  feat/warn-non-existing-variables[m
  fix/blits-attr-vs-code[m
  fix/computed-prop-as-for-loop-data[m
  fix/for-loop-index-variable[m
  fix/intercept-type-def[m
  fix/object-assing-operator-effects[m
  fix/show-alpha-issue[m
  fix/test-cases[m
  fix/transition-re-starting[m
  master[m
  verify-2.8.0[m
* [32mverify-again[m
  verify-work-flow[m
