
name: Run Blits Tests

on:
  pull_request:
    branches:
      - dev

jobs:
  run-blits-tests:
    runs-on: ubuntu-latest
    outputs:
      tests_summary: ${{ steps.extract-test-summary.outputs.tests_summary }}

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20.16.0

    - name: Install Dependencies
      run: npm install

    - name: Run Tests
      run: npm run test > test-report.txt
      #To ensure subsequent steps run even if tests fail
      continue-on-error: true

    - name: Extract Test Summary
      id: extract-test-summary
      run: |
        # Search for a line containing both "passed:" and "failed:"
        summary=$(grep -E "passed:.*failed:" test-report.txt | head -n1)

        # Extract the number of failed tests
        failed=$(echo "$summary" | sed -E 's/.*failed:\s*([0-9]+).*/\1/')

        echo "tests_summary=$summary" >> $GITHUB_ENV

        # If the number of failed tests is greater than 1, exit with error.
        if [ "$failed" -gt 1 ]; then
            exit 1
        fi
      outputs:
          test_summary: ${{ env.tests_summary }}

    - name: Upload Test Report Artifact
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-report
        path: test-report.txt
